export const adminResources = {
  posts: {
    table: "blog_posts",
    label: "Artigos do blog",
    singular: "artigo",
    description: "Crie, edite e publique conteúdos para o blog.",
    orderBy: "published_at",
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, autoGenerated: true },
      { name: "thumbnail", label: "Thumbnail do card", type: "imageUpload" },
      { name: "image", label: "Imagem hero", type: "imageUpload", required: true },
      { name: "author", label: "Autor", type: "text", required: true },
      {
        name: "category",
        label: "Categoria",
        type: "select",
        required: true,
        options: [
          "UX & Conversão",
          "Websites",
          "Branding & Identidade Visual",
          "Marketing Digital",
          "Estudos de Caso",
          "UX Insights",
        ],
      },
      { name: "excerpt", label: "Resumo", type: "textarea", required: true },
      { name: "published_at", label: "Data de publicação", type: "date" },
      { name: "reading_time", label: "Tempo de leitura", type: "text", required: true },
      { name: "intro", label: "Introdução", type: "textarea", required: true },
      { name: "content", label: "Corpo do artigo", type: "richtext", required: true },
    ],
  },
  projects: {
    table: "projects",
    label: "Projetos",
    singular: "projeto",
    description: "Gerencie os cases e projetos exibidos no site.",
    orderBy: "published_at",
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "description", label: "Descrição curta", type: "textarea" },
      {
        name: "full_description",
        label: "Descrição completa",
        type: "richtext",
      },
      { name: "meta_description", label: "Texto do card", type: "textarea" },
      { name: "thumbnail", label: "Thumbnail do card", type: "imageUpload" },
      { name: "image", label: "Imagem principal", type: "imageUpload" },
      { name: "image_2", label: "Imagem complementar 1", type: "imageUpload" },
      { name: "image_3", label: "Imagem complementar 2", type: "imageUpload" },
      { name: "image_4", label: "Imagem complementar 3", type: "imageUpload" },
      { name: "image_5", label: "Imagem complementar 4", type: "imageUpload" },
      { name: "alt", label: "Texto alternativo", type: "text" },
      { name: "published_at", label: "Data de publicação", type: "date", required: true },
      { name: "external_url", label: "URL externa", type: "url" },
    ],
  },
};

export function getEmptyRecord(fields) {
  return fields.reduce((record, field) => {
    record[field.name] = "";
    return record;
  }, {});
}
